AzureAD/azure-activedirectory-library-for-python

- adal/argument.py
- adal/authentication_context.py
- adal/authentication_parameters.py
- adal/authority.py
- adal/cache_driver.py
- adal/code_request.py
- adal/constants.py
- adal/log.py
- adal/mex.py
- adal/oauth2_client.py
- adal/self_signed_jwt.py
- adal/token_cache.py
- adal/token_request.py
- adal/user_realm.py
- adal/util.py
- adal/wstrust_request.py
- adal/wstrust_response.py
- adal/xmlutil.py
also resolve conflicts with recent test fixups
> address review feedback from brettcannon

- adal/__init__.py
- setup.py
To clear confusions for code reviewers and potential upgrading issues for internal users.
/CC: @addev-ashish
> release: version at 0.3.0

- adal.pyproj
- adal/authentication_context.py
- adal/authority.py
- adal/cache_driver.py
- adal/constants.py
- adal/mex.py
- adal/oauth2_client.py
- adal/token_request.py
- adal/wstrust_request.py
- adal/wstrust_response.py
- tests/mex/usystech.mex.xml
- tests/test_mex.py
- tests/test_username_password.py
- tests/test_wstrust_request.py
- tests/test_wstrust_response.py
- tests/util.py
Summary:
a. Fix issue #29 and #1
b. Port over the wstrust2005 support from node version and other features work in this area.
c. Fix all skipped tests on username & password flow as both #a and #b need it.
~~Mark it as `do not merge` as code is not fully finalized, though the structuring is done.~~
> Fix all known issues in federated account login

- adal/__init__.py
- setup.py
/CC:@addev-ashish.
I plan to publish a new version today. Let me know if there are other fixes you like get in
> version: update to 0.4.0

- README.md
- RELEASES.md
- adal.pyproj
- adal/__init__.py
- adal/authentication_context.py
- adal/authority.py
- adal/cache_driver.py
- adal/constants.py
- adal/mex.py
- adal/oauth2_client.py
- adal/token_request.py
- adal/user_realm.py
- adal/wstrust_request.py
- adal/wstrust_response.py
- setup.py
- tests/mex/usystech.mex.xml
- tests/test_mex.py
- tests/test_username_password.py
- tests/test_wstrust_request.py
- tests/test_wstrust_response.py
- tests/util.py
Currently the dev branch is falling behind the master. This merge brings the previous 16 commits on master back to dev. I did not change anything else. Future developments will happen on dev branch first.
@addev-ashish @yugangw-msft
> Merging master branch into dev

- setup.py
Resolves AzureAD/azure-activedirectory-library-for-python#38
CC @addev-ashish @yugangw-msft
> No longer need to repeat the version number change in future releases

- adal/__init__.py
- sample/device_code_sample.py
- sample/refresh_token_sample.py
Would like to push out a new release for the change tracked by #44 
Also including fix a minor typo in the sample
//cc @rayluo
> version updates for release

- setup.py
> setup.py shall not import adal

- adal/__init__.py
> release:update adal version

- adal/__init__.py
- adal/authentication_context.py
- adal/log.py
- adal/oauth2_client.py
- setup.py
- tests/test_api_version.py
- tests/test_log.py
After review, this PR will be merged back to master branch, and become the release of 0.4.3
@yugangw-msft Please review the changelog (which will be included in the release notes):
* Fixes logger bug to ensure proper logging (#55)
* Updates dependency to exclude the requests package 2.12.* (#58)
* Introduces a new switch to override the default behavior (#57)
> Release 0.4.3

- setup.py
This reverts commit b9affeb5035e41a80e56053c054ce22ea3039b37. See discussion in #58 and #61. Once merged, this PR will resolve #61.
> Revert "skip 2.12.* request package due to known issues (#58)"

- adal/__init__.py
- setup.py
* Revert a workaround introduced in 0.4.3, we now have better understanding and recommend a different way to solve it. (#61)
> Release 0.4.4

- adal/constants.py
> Add new login.microsoftonline.us

- README.md
Otherwise error happens during subsequent "pip install cryptography".
> Emphasize on "upgrade to the latest pip"

- adal/oauth2_client.py
> Bubble up server response on error

- sample/certificate_credentials_sample.py
- sample/client_credentials_sample.py
- sample/device_code_sample.py
- sample/refresh_token_sample.py
- sample/website_sample.py
Addressing @yugangw-msft 's [feedback in another PR](https://github.com/AzureAD/azure-activedirectory-library-for-python/pull/96#discussion_r127126737).
> Customizable resource in all samples

- README.md
- sample/refresh_token_sample.py
This PR replaces the outdated PR #94 .
> Clarify when client_secret is needed

- adal/wstrust_request.py
> Add timeout for WSTrust

- adal/token_cache.py
This PR has been tested by customer (thanks Ace-E4s!) It will resolve #123 . The discussion in detail is also archived in #123.
> Fix for thread racing issue in cache.remove()

- sample/certificate_credentials_sample.py
- sample/client_credentials_sample.py
- sample/device_code_sample.py
- sample/refresh_token_sample.py
- sample/website_sample.py
> Mentions the new wiki page in samples

- adal/__init__.py
- adal/authentication_context.py
- adal/authority.py
- adal/constants.py
- adal/token_request.py
- tests/test_authority.py
- tests/test_self_signed_jwt.py
Each individual PR referenced below has been previously reviewed and accepted. The current PR organizes the release process. The following content will become release notes.
- Enhancement: Added authorization code flow support for public clients (#149)
- Enhancement: Added Proof Key for Code Exchange (PKCE) support in authorization code flow for public clients (#150)
- Enhancement: Raises a value error when the authority url is not in the expected format (#126, #151)
If you want to have a hands-on test, you can grab this release candidate by:
pip install git+https://github.com/AzureAD/azure-activedirectory-library-for-python.git@release-0.7.0
> ADAL Python 0.7.0

- adal/__init__.py
- adal/authentication_context.py
- sample/certificate_credentials_sample.py
- sample/client_credentials_sample.py
- sample/device_code_sample.py
- sample/refresh_token_sample.py
- sample/website_sample.py
- tests/test_api_version.py
- tests/util.py
Merge release-1.0.0 back to dev
> Release 1.0.0 with changed behavior

- README.md
- adal/__init__.py
- adal/authority.py
- tests/test_authority.py
- Relaxing authority url check (#156,#157)
> ADAL Python 1.0.1

- adal/__init__.py
- adal/authority.py
- tests/test_authority.py
- Fixing incorrect cache operation in authorization code flow (#161)
> ADAL Python 1.0.2

- adal/__init__.py
> Merge ADAL Python 1.2.0 PR back to dev

- adal/self_signed_jwt.py
> Usability enhancement in Subject Name and Issuer Authentication input 

- adal/self_signed_jwt.py
- setup.py
Make it compatible with PyJWT 1 & 2.
Also declare upper bound for requests and python-dateutil.
> Make it compatible with PyJWT 1 & 2

- .github/ISSUE_TEMPLATE/a-template-reminding-adal-s-status.md
- adal/__init__.py
- adal/token_request.py
- adal/user_realm.py
- adal/wstrust_request.py
Each of the sub-PRs included in this release has been tested and reviewed and approved in their individual PR. The purpose of this all-in-one release PR is to organize the release process. Please review/proof-read the following release notes.
Release Notes:
* Previous ADAL versions would incorrectly pick up the latest PyJWT 2.x but would not be compatible with it. In this new release, ADAL will be compatible with both PyJWT 1.x and 2.x. (#245, #246)
> Release 1.2.6

- adal/__init__.py
> Merge ADAL Python 1.2.6 back to dev branch

- README.md
Developer loyalty survey link added to README.md file.
> survey link added to README.md

- adal/wstrust_response.py
> Use utf-8 instead of us-ascii for saml token
