README.md, sample/client_credentials_sample.py, sample/device_code_sample.py, sample/refresh_token_sample.py
=> refresh readme

adal/__init__.py, requirements.txt, setup.py
For requests and pyjwt, set to the one with first major version update.
For dateutil, set to 2.1.0, the first which support both 2.x and 3.x
For  cryptography, pick 1.1 which is the first which can install on windows error free.
Tested windows, osx and linux.
=> Set version range on dependency packages

adal/constants.py, tests/test_authority.py, tests/util.py
This change adds 2 federation providers to the whitelist of federation
providers in the ADAL library
1. The US government one (login-us.microsoftonline.com)
2. The German government one (login.microsoftonline.de)
=> Update for US Government and German Government Authority Instances

README.md
Address #27 
/CC:@addev-ashish
=> readme: add explanation for requiring client-id and resource

README.md, adal/authentication_context.py, adal/authority.py, adal/mex.py, adal/oauth2_client.py, adal/user_realm.py, adal/wstrust_request.py
Mainly for tracing through proxy
=> expose ADAL_PYTHON_SSL_NO_VERIFY to skip cert verification 

adal/authority.py, adal/mex.py, adal/oauth2_client.py, adal/user_realm.py, adal/wstrust_request.py
The real error was hidden under the exception of `'ascii' codes can't encode character u'\xa0' in position 150: ordinal not in range(128)`. This is confusing
=> fix encoding error when format error text (python 2.7 only)

adal/oauth2_client.py, tests/test_username_password.py
Surfaced through azure/azure-cli#1086
Python 3.5 already defaults to 'utf-8' which works fine, but 2.7 defaults to 'ascii' which is broken.
So this simple PR ensure to use UTF-8 always
=> use utf-8 to decode id_token which could contain unicodes display names

adal/authentication_context.py, adal/oauth2_client.py, tests/test_api_version.py
In an attempt to fix #54 yet maintain backward compatibility, this PR introduces a parameter AuthenticationContext(..., api_version='1.0') to turn on/off api-version behavior.
* Legacy ADAL-python customers can safely upgrade to the upcoming new version which contains this adjustment. By default, your current code will still work with the SAME behavior as before.
* However, to ensure a smooth transition, we recommend the current ADAL-python customers to try out the new behavior by explicitly set `context = AuthenticationContext(..., api_version=None)`, to confirm that your app will work fine with this new direction.
* New ADAL-python customers shall use `context = AuthenticationContext(..., api_version=None)` too. In future, this switch will have a default value as `None`.
=> Introduce a parameter AuthenticationContext(..., api_version='1.0')

.travis.yml, setup.py
[Python 3.6 has been officially released](https://www.python.org/downloads/release/python-360/). We are now examining our code on Python 3.6. All test cases in our current code base actually pass on Python 3.6, however the Travis-CI test jobs failed due to the source code style checker [PyLint does not yet support Python 3.6](https://github.com/PyCQA/pylint/issues/1241). We don't have to run PyLint on every Python platform so, as a quick workaround, let's bypass it for now.
=> Python 3.6 support

adal/util.py
Sets the platform header to 'unknown' in case of an exception during the architecture resolution call. Tested the fix in a Gunicorn environment.
UPDATE: Since the issue is caused by `platform.architecture(...)` fails on Gunicorn environment, we end up using an [alternative way](https://docs.python.org/3/library/platform.html#cross-platform) to detect.
=> Fixes platform resolution issue in Gunicorn/Gevent context

sample/certificate_credentials_sample.py, sample/client_credentials_sample.py, sample/device_code_sample.py, sample/refresh_token_sample.py, sample/website_sample.py
Usage in the sample codes comment stated `python sample.js parameters.json`.  Updated to read `python sample.py parameters.json`.
=> Corrected usage in comment of sample code

sample/client_credentials_sample.py, sample/refresh_token_sample.py
You just need to disable authority validation.
These have been tested on an AD FS 2016 server.
=> Demonstrating how ADAL supports ADFS-only scenario

adal/cache_driver.py, tests/test_cache_driver.py
This fixes #82, which was caused by the cache implementation was trying to refresh an entry, but ended up with an exception because the cached entry came from a previous `acquire_token_with_client_credentials(...)` call contained no RT. This fix will skip the refresh attempt when there is no RT. A new unit test case is also included.
From the library user's perspective, the intuitive way to manually reproduce #82 before this fix, and to verify the new behavior after this fix, is to duplicate the `acquire_token_with_client_credentials(...)` call [at the end of this sample](https://github.com/AzureAD/azure-activedirectory-library-for-python/blob/0.4.5/sample/client_credentials_sample.py#L46-L52), and see the presence and absence of the exception, before and after this fix.
=> Do not attempt to refresh when RT is unavailable

setup.py
Otherwise some locale uses default ascii decoding and can not handle BOM.
This PR fixes #89, and already tested by its reporter @glaubitz . This fix will allow him to build a RPM package and that will drive our adoption in the community.
=> Forcing utf8 decoding

sample/certificate_credentials_sample.py, sample/client_credentials_sample.py, sample/device_code_sample.py, sample/refresh_token_sample.py, sample/website_sample.py
=> Demonstrating how to properly set api_version=None in all samples

README.md, sample/certificate_credentials_sample.py, sample/client_credentials_sample.py, sample/device_code_sample.py, sample/refresh_token_sample.py, sample/website_sample.py
And guide readers to the runnable samples.
The reason of this change is that,  [we used to have ONLY those code snippets in README but WITHOUT any real samples](https://github.com/AzureAD/azure-activedirectory-library-for-python/tree/903448df0efbfc63ae31d7dcd940f88cbed15f01). Later we [added real samples and modified readme to include links to those samples](https://github.com/AzureAD/azure-activedirectory-library-for-python/pull/13/files). This opened the door for the 2 copies of information becoming out of sync. In practice, we the maintainers pay more attention on real samples because they are runnable and we used them to test all the time, and we sometimes overlook the README. This kind of out-of-sync README could be [costy](https://github.com/AzureAD/azure-activedirectory-library-for- …
=> Remove outdated code snippets in README

adal/cache_driver.py, tests/test_refresh_token.py
@rayluo, I will add you to a mail thread with more details
For context, Azure Stack environment uses ADFS 2016. When use MRRT (`multi resource refresh token`) to get an access token for other resources, server doesn't include `resource` in the response payload because it doesn't return a new refresh token. Note, AAD always returns a new refresh token. The consequence is pretty severe, as `resource` is part of the token cache key, and not updating it will corrupt the whole cache.
The change is pretty safe. If you are fine with the option, I will go ahead and add a few test coverage.
=> Handle token refresh in Azure Stack (ADFS 2016) 

adal/authentication_context.py, adal/oauth2_client.py
Add ability to pass requests (connect,read) timeout parameters.
=> Add requests timeout

adal/authority.py, adal/mex.py, adal/oauth2_client.py, adal/user_realm.py, adal/wstrust_request.py
**Motivation**: If AAD is under heavy traffic, it would return a response with [HTTP 429 status code and a Retry-After header](https://httpstatuses.com/429). Previously this information was not bubbled up to the app developers by ADAL Python.
**Implementation**: This PR provides such information by raising the underlying [`requests.HTTPError`](http://docs.python-requests.org/en/master/_modules/requests/models/#Response.raise_for_status) exception, which wraps the entire raw response so app developers have access to the response headers. The usage pattern would look like this.
import requests
try:
resp = requests.get('https://httpbin.org/status/429')
resp.raise_for_status()
print("If you reach this line, there is no error")
except requests.HTTPError as e:
print("Retry after %s", …
=> Surface HTTPError exception on 429

adal/authentication_context.py
This PR adds an booolean `enable_pii` flag for previous PR #111, therefore resolves #114.
If you want to have Personally Identifiable Information (PII) included in log, you just add one more optional parameter to the AuthenticationContext(...):
ac = AuthenticationContext(..., enable_pii=True)
ac.acquire_token...(...)
=> AuthenticationContext(...) adds an enable_pii flag

adal/wstrust_response.py, tests/test_wstrust_response.py
We received ~yet another~ two customer support cases, about unable to authenticate on a federated ADFS environment. And this time we found the clue (thanks @yugangw-msft !), came up with a fix, deployed and tested the patch on that customer's environment. We are now preparing a formal PR for the fix.
You can test this PR by `pip install git+https://github.com/AzureAD/azure-activedirectory-library-for-python.git@return-xml-as-is`
This PR will fix #80
=> Return xml as is

adal/authentication_context.py, adal/authority.py, adal/mex.py, adal/oauth2_client.py, adal/user_realm.py, adal/wstrust_request.py
Hi,
I work with @yugangw-msft in the SDK/CLI team. I'm migrating the Autorest internal authentication system to use 100% of ADAL, so all SDK/CLI queries pass through it.
Part of my migration, I realized that my current implementation support verify/proxies as context parameters, where ADAL does not. This PR is just passing through `requests` verify/proxies. No breaking changes, just let the options pass to `requests`. Documentation strings are taken from `requests` directly.
Reference:
http://docs.python-requests.org/en/master/user/advanced/#proxies
Let me know if you have questions (internal email or here)
Thank you!
Laurent
=> Add verify and proxies to context

adal/__init__.py, adal/authentication_context.py, sample/certificate_credentials_sample.py, sample/client_credentials_sample.py, sample/device_code_sample.py, sample/refresh_token_sample.py, sample/website_sample.py, tests/test_api_version.py, tests/util.py
We are planning for a 1.0.0 ~~rc1~~ release. The following content will become release note:
* It will include [a breaking change which we have planned for more than 1 year now](https://github.com/AzureAD/azure-activedirectory-library-for-python/blob/0.5.1/adal/authentication_context.py#L68-L72).
The default value of `api_version` parameter in the `AuthenticationContext` constructor will be changed from "1.0" to None. The [previous default value "1.0" was a middleground between backward compatibility and new behavior](https://github.com/AzureAD/azure-activedirectory-library-for-python/pull/57), but it was not very noticeable and people occasionally [forgot to opt-in for the new behavior](https://github.com/AzureAD/azure-activedirectory-library-for-python/pull/102).
Now we will enable the …
=> ADAL Python 1.0.0 (was Release Candidate 1.0.0rc1)

README.md, adal/__init__.py, adal/authentication_context.py, adal/token_request.py, sample/certificate_credentials_sample.py, sample/client_credentials_sample.py, sample/device_code_sample.py, sample/refresh_token_sample.py, sample/website_sample.py, tests/test_api_version.py, tests/util.py
Remove duplication. Moved removed content into wiki.
=> Link to wiki from Readme.

README.md, adal/authority.py, tests/test_authority.py
This relaxes the authority url check to allow customers to add slashes after the tenant. 
It then normalizes the url by removing these extra slashes. 
Solves #156
=> Relax authority check

adal/token_request.py
//CC: @rayluo 
My Change #138 was not right by searching the cache before sending out the request because at that time we don't know the userID, so the entry returned from cache might be issued to other users.
So I am reverting it and replace with the right fix, which is one line change like we did on [device code](https://github.com/AzureAD/azure-activedirectory-library-for-python/blob/dev/adal/token_request.py#L404)
The unit test introduce by #138 is still kept as it verifies the right scenario, that the token from the wire response will be saved in cache.
=> fix an incorrect cache operation on authorization code flow

requirements.txt
We update our dev and test environment to use cryptography 2.3, the [current latest version](https://cryptography.io/en/latest/changelog/). The Travis-CI job is [using such latest version now](https://travis-ci.org/AzureAD/azure-activedirectory-library-for-python/jobs/415693509#L432), and all existing test cases still pass.
PS: The real dependency in production has long been set up to [use latest version](https://github.com/AzureAD/azure-activedirectory-library-for-python/blob/1.0.2/setup.py#L79) all the time.
=> Upgrade crytography to 2.3 in requirements.txt

adal/authority.py, adal/constants.py, tests/test_authority.py
Add support for dSTS by white-listing dSTS domains so that this library can be used to request Oauth2 tokens from dSTS.
=> Add support for dSTS enpoints

adal/__init__.py, adal/authority.py, adal/constants.py, tests/test_authority.py
Each individual PR referenced below has been previously reviewed and accepted. The current PR organizes the release process. The following content will become release notes.
* Enhancement: Added whitelisted domains for dSTS (#164)
If you want to have a hands-on test, you can grab this release candidate by:
pip install git+https://github.com/AzureAD/azure-activedirectory-library-for-python.git@release-1.1.0
/CC @jmstimso
=> Release 1.1.0

adal/authentication_context.py, adal/self_signed_jwt.py, adal/token_request.py, tests/test_self_signed_jwt.py, tests/util.py
Minimum change. Naming and logic are chosen based on dotnet version.
Once the mechanism is approved, i will add test coverage
=> [client certificate]: support sn+issuer authentications

requirements.txt
Pick up the [vulnerability fix in requests 2.20.0](https://github.com/requests/requests/blob/master/docs/community/vulnerabilities.rst#previous-cves)
=> Update requirements.txt to requests 2.20.0

adal/token_cache.py
Don't skip `__ne__()` in Python 2, per https://stackoverflow.com/questions/4352244/python-should-i-implement-ne-operator-based-on-eq
=> Add __ne__() in TokenCacheKey

adal/token_request.py
Our internal source code analysis tool discovers this issue. 
That code path was actually a fall-back option, which was rarely hit. That's probably why it exists for 3 years without causing trouble. We are fixing it now.
=> Fix inaccurate re

adal/token_request.py
Get rid of really annoying info message I see in my terminal when running my code with debug level set to Info
I see this message appear every half a second, if it's that frequent it shouldn't be an info level message.
=>  Change info to debug for message

adal/token_request.py, adal/util.py
Related to issue https://github.com/AzureAD/azure-activedirectory-library-for-python/issues/122. I'm only addressing the log entries I think should be debug instead of logging. Not sure about the other logging mentioned in the issue.
=> Changed info log level to debug log level for debug logs

adal/authority.py, tests/test_authority.py
This is an attempt to fix #201 . It would generate a record-breaking long description like this:
> ~ValueError: The path of authority_url, also known as the tenant, should be a domain name like mycompany.onmicrosoft.com or a GUID style of tenant id. Your tenant input "https:/example.com/foo/bar" and your entire authority_url "https://login.microsoftonline.com/https://example.com/foo/bar" do not look like that.~
> ValueError: The path of authority_url (also known as tenant) is invalid, it should either be a domain name (e.g. mycompany.onmicrosoft.com) or a tenant GUID id. Your tenant input was "https:/example.com/foo/bar" and your entire authority_url was "https://login.microsoftonline.com/https://example.com/foo/bar"
If you want to have a hands-on test, you can probably grab this patch …
=> Reword the ValueError text when tenant is not right

adal/authority.py, adal/constants.py, tests/test_authority.py
Enable dynamic whitelisting of dSTS endpoints to support new buildouts of national cloud environments.
UPDATED info quoted from PR conversation:
The new authority.py implementation for dSTS is to support (future) new cloud environments in which we will not be allowed to explicitly whitelist endpoints in public GitHub repos due to customer restrictions on releasing DNS names. Since I have removed dSTS whitelisting constants, these test cases should be sufficient to cover all current and future dSTS endpoints that fit the .dsts. DNS address pattern.
=> Enable dynamic whitelisting of dSTS endpoints to support new buildouts

README.md, docs/source/index.rst
Currently some customers would still land on ADAL Python materials, such as, #218.
This change in README would help us guide customers to MSAL Python.
@navyasric @abhidnya13 please proofread. CC: @henrik-me 
Once we finalize on the wording, we can also add same changes into ADAL Python's API reference docs, and its wiki home page.
=> Advertise MSAL Python

adal/authentication_context.py
Backport [MSAL PR 185](https://github.com/AzureAD/microsoft-authentication-library-for-python/pull/185) to ADAL, so we also fix #225 here.
ADAL is in bugfix mode now, so we won't cut a new release for this. And we don't need to, because this documentation change would be published, once this PR is merged.
CC @mbearup
=> Backport MSAL PR #185 to ADAL

adal/authentication_parameters.py, adal/constants.py, adal/log.py, sample/website_sample.py, tests/config_sample.py, tests/test_api_version.py, tests/test_authority.py, tests/test_self_signed_jwt.py, tests/test_user_realm.py, tests/util.py
Login.windows.net needs to be replaced by login.microsoftonline.com.  Also removing legacy US Gov endpoint that has been retired (login-us.microsoftonline.com)
---
Notes (by Ray): This PR will fix #224.
=> Removal of login.windows.net / login-us

setup.cfg, setup.py
The substantial changes in this PR is only this: `It is now SUPERSEDED by MSAL Python.` The [longer description in current README](https://github.com/AzureAD/azure-activedirectory-library-for-python/blame/1.2.3/README.md#L3-L12) will be automatically picked up in next release.
This will fix https://github.com/AzureAD/microsoft-authentication-library-for-python/issues/192
---
It is confirmed, [PyPI does not allowed a project's metadata to be updated without a new release](https://github.com/pypa/warehouse/issues/2170). Precisely speaking:
* PyPI records metadata for each release (thus they are immutable - which is reasonable);
* PyPI does not store metadata for a project, which is a surprise;
* And then PyPI misleadingly displays the latest release's metadata for a project, which is …
=> Update metadata for next release

adal/token_request.py, adal/user_realm.py, adal/wstrust_request.py
While testing for migration of Fairfax,  username-password federated was failing, this PR includes the fix.
The problem was ADAL was hardcoding Cloud_audience_urn which is now fetched from the mex response.
=> Federated flow fix

.github/ISSUE_TEMPLATE/a-template-reminding-adal-s-status.md, adal/__init__.py, adal/token_request.py, adal/user_realm.py, adal/wstrust_request.py
* Bugfix to address error "InvalidScope : FaultMessage: ID3082: The request scope is not valid or is unsupported." when using username-password flow with federated user account while your tenant is migrating to a different cloud. (#240)
=> Release 1.2.5
